In [1]:
import pandas as pd

In [22]:
df = pd.read_csv("clevelandvudssofar.csv")

In [23]:
df = df[df['Recivedtxtfiles'].notna()]

In [24]:
df = df[df['age'].notna()].reset_index()

In [26]:
df.head()

,index,patient id,Urodynamics Date,combo,Textfile,Recivedtxtfiles,age,ebc,Patentoncrosswalk,review1,review2,review3,avg_rating
0,0,061f78ea-ffc9-405d-985c-d516888aaae3,44937,061f78ea-ffc9-405d-985c-d516888aaae344937,122b,122b,2.0,120,Y,1,1,1,1
1,1,07aa0770-de0f-4d2f-884a-683f7306cfd8,43418,07aa0770-de0f-4d2f-884a-683f7306cfd843418,14b,14b,3.0,150,Y,2,3,2,2
2,2,0b8f12fd-177b-4abc-b1ef-50202ce0fa56,45260,0b8f12fd-177b-4abc-b1ef-50202ce0fa5645260,196b,196b,8.0,300,Y,1,1,2,1
3,4,20004dde-d615-404f-98e7-8310553f1eba,45372,20004dde-d615-404f-98e7-8310553f1eba45372,241b,241b,31.0,500,Y,2,2,2,2
4,6,23ae1591-f52f-4f1f-b971-1ddd630505b5,45155,23ae1591-f52f-4f1f-b971-1ddd630505b545155,167b,167b,17.0,500,Y,1,1,1,1

In [25]:
df.columns = df.columns.str.strip()
df['avg_rating'] = ((df['review1'] + df['review2'] + df['review3']) / 3).round(0).astype(int)
df = df.drop(columns=['Study'])

In [27]:
df.isna().sum()

index                0
patient id           0
Urodynamics Date     0
combo                0
Textfile             0
Recivedtxtfiles      0
age                  0
ebc                  0
Patentoncrosswalk    0
review1              0
review2              0
review3              0
avg_rating           0
dtype: int64

In [30]:
df.head(2)

,index,patient id,Urodynamics Date,combo,Textfile,Recivedtxtfiles,age,ebc,Patentoncrosswalk,review1,review2,review3,avg_rating
0,0,061f78ea-ffc9-405d-985c-d516888aaae3,44937,061f78ea-ffc9-405d-985c-d516888aaae344937,122b,122b,2.0,120,Y,1,1,1,1
1,1,07aa0770-de0f-4d2f-884a-683f7306cfd8,43418,07aa0770-de0f-4d2f-884a-683f7306cfd843418,14b,14b,3.0,150,Y,2,3,2,2

In [31]:
df["study_id"] = df["Textfile"]

In [32]:
df.to_csv("clevelandmani.csv", index=False)